### ISSUE TITLE
Avoid hardcoding usernames and variables when possible

### ISSUE THREAD

**Issue by lwbt** [nickjj/dotfiles#10]
Hello Nick, thank you for your videos and posts. I found them very helpful, informative and reasonably short.

I understand that these are *your* dotfiles but it may benefit users to replace the following line in .vrimrc:

```
let g:mkdp_markdown_css='/home/nick/.local/lib/github-markdown-css/github-markdown.css'
```
with this:
```
let g:mkdp_markdown_css='/home/'.$USER.'/.local/lib/github-markdown-css/github-markdown.css'
```

It worked for me, but you know certainly more about configuring vim than me.

Why may this be an issue? I'm running and *automatically* syncing my dotfiles to a few computers, among them Chomebooks with Crostini were I was not able to set a custom  username until a few weeks (months?) ago.

**Comment by nickjj** [comment]
Hey,

Thanks, that's a good idea. I didn't even know you could reference environment variables in a vimrc file.

Maybe we can roll with:  
 `let g:mkdp_markdown_css=$HOME.'/.local/lib/github-markdown-css/github-markdown.css'`

But I do wonder how it's going to treat paths with spaces. Going to Google this one a bit.

**Comment by lwbt** [comment]
Sorry no, I don't have much experience.

**Comment by nickjj** [comment]
Ok, I'm going to go with it.

It's been pushed to master in https://github.com/nickjj/dotfiles/commit/d0971cc6ba7accd83b4cd73979932ac4f9d42682.

Thanks!
