### ISSUE TITLE
Suggestion: include .vimrc

### ISSUE THREAD

**Issue by somemorwater** [nickjj/dotfiles#11]
In order to use the vim plugin manager the user needs to have configured a .vimrc.   The instructions were really useful in general, but it would greatly assist newer users if they included a decent .vimrc and included the line to setup the plugin dir.
e.g. :
call plug#begin('~/.vim/autoload')

This needs to be before the section in your guide https://github.com/nickjj/dotfiles#install-plugins-for-vim-and-tmux

**Comment by nickjj** [comment]
Hi,

There is a [`.vimrc` file included](https://github.com/nickjj/dotfiles/blob/master/.vimrc) and it's also symlinked near the start of the instructions.

Did something go wrong where that vimrc didn't end up being symlinked?

**Comment by somemorwater** [comment]
Aww.  I see the file your talking about and I figure out what happened.   The  large command to create all the links failed when it tried to create a symlink for .bashrc because it had already been created by the default installation:  
$  lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

> mkdir -p ~/.local/bin && mkdir -p ~/.vim/spell \
>   && ln -s ~/dotfiles/.aliases ~/.aliases \
>   && ln -s ~/dotfiles/.bashrc ~/.bashrc \
>   && ln -s ~/dotfiles/.gemrc ~/.gemrc \
>   && ln -s ~/dotfiles/.gitconfig ~/.gitconfig \
>   && ln -s ~/dotfiles/.profile ~/.profile \
>   && ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf \
>   && ln -s ~/dotfiles/.vimrc ~/.vimrc \
>   && ln -s ~/dotfiles/.vim/spell/en.utf-8.add ~/.vim/spell/en.utf-8.add \
>   && ln -s ~/dotfiles/.local/bin/set-theme ~/.local/bin/set-theme \
>   && sudo ln -s ~/dotfiles/etc/wsl.conf /etc/wsl.conf


It appears that it did not perform any of the link commands after the attempted link to .bashrc.

**Comment by somemorwater** [comment]
I ran the link commands and after having moved the default .bashrc and .profile files and everything worked fine,

**Comment by nickjj** [comment]
Ah, hmm I could add `-f` flags to all of the symlink commands in the docs and that would forcefully create them but this also means it would perform a destructive action of deleting your original files which might upset folks if they run the commands without reading it. Maybe I could get around that with a warning before running the commands.

**Comment by somemorwater** [comment]
This sounds like an optimal solution.  The warning should be sufficient for those who care about their original files.

**Comment by nickjj** [comment]
Ok, hopefully no one will miss the warning haha. I just pushed an update at: https://github.com/nickjj/dotfiles#-super-ultra-important-warning-

Thanks for reporting this!

**Comment by somemorwater** [comment]
ROFL, yup.. couldn't miss that warning.. Thanks for updating things so quickly:)
