### ISSUE TITLE
Error No such file or directory, on set-theme script

### ISSUE THREAD

**Issue by R1skNt** [nickjj/dotfiles#12]
Hello Nick,
there is an error when trying to set a theme when running
`set-theme one`
 this is the output

`Traceback (most recent call last):
  File "./set-theme", line 186, in <module>
    main()
  File "./set-theme", line 179, in main
    change_terminal_theme(theme, bg)
  File "./set-theme", line 115, in change_terminal_theme
    for line in f:
  File "/usr/lib/python3.8/fileinput.py", line 248, in __next__
    line = self._readline()
  File "/usr/lib/python3.8/fileinput.py", line 342, in _readline
    os.rename(self._filename, self._backupfilename)
FileNotFoundError: [Errno 2] No such file or directory: '/c/Users/xxxx/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json' -> '/c/Users/xxxx/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json.bak'`

and the path actually contain these settings files `settings.json.2021-07-19T14-34-37.backup` and  `settings.json`

I have a clean install of Ubuntu 20.04 on wsl2 using windows terminal.

**Comment by nickjj** [comment]
Hi,

If it says no such file, it's not there.

Did you try copy / pasting the path exactly from the error message to your terminal to see if the path exists?

**Comment by R1skNt** [comment]
I did a reset to the windows terminal and rerun the script and it works now, but the file was there! it's strange what happened
anyhow, thanks for the amazing work, Nick.
