### ISSUE TITLE
Screen black if I change to light version then it's white without any color.

### ISSUE THREAD

**Issue by whynot2018** [nickjj/dotfiles#19]
Hi 
I try dotfiles under Mac OS 13.4 installation works fine. But if I try to start vim without or with tmux it's always black screen. Is there any changes I should be done? by the way set-theme doesn't work under Mac OS. I assume it's only for Powershell.
Best regards.

**Comment by nickjj** [comment]
Can you show a screenshot?

Yep `set-theme` will only work if you're using the Microsoft Terminal. If you're using iTerm2 if you can set the theme manually in the UI of that program.

**Comment by whynot2018** [comment]
iTerm2 I don't think so. Macos terminal and dotfiles installed zsh.
$ sw_vers
ProductName:            macOS
ProductVersion:         13.4
BuildVersion:           22F66

![screen](https://github.com/nickjj/dotfiles/assets/48062504/c63c1e2f-6889-44b5-b31c-4891e8e4ee44)

**Comment by nickjj** [comment]
Did all of the plugins install successfully?

I'm using these dotfiles on macOS with iTerm2 on my work machine and can't reproduce that.

I'm going to be traveling today so I can't check my work machine but I don't remember changing anything in iTerm2 other than what's called out in the comments of my vimrc:

> " Using iTerm2? Go-to preferences / profile / colors and disable the smart bar
> " cursor color. Then pick a cursor and highlight color that matches your theme.
> " That will ensure your cursor is always visible within insert mode.

But I will check back tonight or tomorrow.

**Comment by whynot2018** [comment]
Great now it works.
I need to install [iTerm2](https://iterm2.com/).
![screen2](https://github.com/nickjj/dotfiles/assets/48062504/be5c4ab8-aa42-4ea5-b502-aa4bb1382a35)
Bon voyage!
