### ISSUE TITLE
.tmux.conf styles

### ISSUE THREAD

**Issue by ninovasc** [nickjj/dotfiles#2]
In `.tmux.conf` some styles tags dont work in the tmux new release (2.9). to fix this this changes need to be made:

**this:**
```
set -g pane-border-fg default
set -g pane-border-bg default
set -g pane-active-border-fg colour250
set -g pane-active-border-bg default

set-window-option -g window-status-current-attr bold
set-window-option -g window-status-current-fg colour223
```
**to this:**
```
set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg=colour250,bg=default

set-window-option -g window-status-current-style bold
set-window-option -g window-status-current-style fg=colour223
```

I found a script in python to change this confs (thanks @tbutts [https://gist.github.com/tbutts/6abf7fb5b948c066bf180922fb37adcf](https://gist.github.com/tbutts/6abf7fb5b948c066bf180922fb37adcf)) in this tmux issue: 
[https://github.com/tmux/tmux/issues/1689](https://github.com/tmux/tmux/issues/1689)

Thanks for your videos and posts!

**Comment by nickjj** [comment]
Hi,

No problem and thanks for the report. I'm only using tmux 2.6 here. Not even Debian Buster is using 2.9 yet in its official repos. I'm not sure if imposing such a new release is a good move since it's going to alienate just about everyone who isn't running Arch.

**Comment by nickjj** [comment]
I pushed a bunch of changes today, one of which is tmux 3.0+ support.
