### ISSUE TITLE
Gnome terminal defaults cause errors

### ISSUE THREAD

**Issue by wwmike** [nickjj/dotfiles#20]
Hello!

I just installed on an ubuntu desktop vm your script and I realized that the .zprofile sets the XDG_...  variables, thus it's not working by default.

For search engines, this was my error message:
```
/home/misi/.config/zsh/.zshrc:.:76: no such file or directory: /fzf/shell/key-bindings.zsh
/home/misi/.config/zsh/.zshrc:.:109: no such file or directory: /fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
/home/misi/.config/zsh/.zshrc:.:110: no such file or directory: /zsh-autosuggestions/zsh-autosuggestions.zsh

```

I've found that the terminal can be configured to run as a login shell under `Profile > Command > Run command as a login shell`
so I wanted to share to spare the digging for others.

**Comment by wwmike** [comment]
These were in the .zshrc , so when one opens up the terminal, it immediately pops up.
Or if you mean the gnome terminal, I just set it manually.

**Comment by nickjj** [comment]
Your initial issue mentioned needing to configure "run command as a login shell". I thought maybe you had to pick a specific command to run. Was this just a checkbox you had to enable it, and not a text field to input a specific command?

**Comment by wwmike** [comment]
Yes, it was just a checkbox. Maybe there's a command as well, I tried to look it up, but so far all I've found is how to change the default terminal :)

**Comment by nickjj** [comment]
Cool, thanks.

There's not much we can do at a dotfiles level to make it work out of the box. Thanks for opening the issue in case someone encounters a similar problem in the future.

If enough folks report the same problem maybe we can add something to the README file to call that out but given this is the first time it's been called out in ~5 years maybe we can leave it here in the issue for now.
