### ISSUE TITLE
possible replacement of asdf

### ISSUE THREAD

**Issue by sassdavid** [nickjj/dotfiles#21]
Hi @nickjj,

Have you heard about `mise`, formerly known as `rtx`?

Check it out at:
- Website: https://mise.jdx.dev
- GitHub: https://github.com/jdx/mise

It's a 'clone' of `asdf` implemented in Rust with a lot of additional features. It handles runtimes differently, making it much faster than `asdf`.

All `asdf` plugins are compatible with `mise`, and it can be used to install Node without `node-build` from pre-compiled source. It implements the Node plugin as a 'core' plugin, allowing its use without any additional plugin installation.

Take a look at it, and let's consider leaving `asdf` behind.

Thank you for these dotfiles and the information they contain.

**Comment by nickjj** [comment]
Hi,

Thanks for opening this, no I haven't heard of this project before. Although I've found that in practice any slowness related to `asdf` is related to things like compiling runtimes if no pre-compiled binaries exist for a specific platform. That's a 1-off use case during installation of a new runtime version and I'm not sure how `mise` would make that process much faster? Have you noticed other cases where `asdf` is slow to the point where switching to `mise` makes a noticeable difference?

My main concern would be supporting languages that aren't listed under languages in https://mise.jdx.dev/getting-started.html. For example if someone using my dotfiles has `asdf` set up to work with PHP, what would that look like for `mise`?

**Comment by nickjj** [comment]
It's probably because I mostly use Docker to contain my apps. The only time I use `asdf` is to run an old version of Ruby / Node for Jekyll. On a Jekyll command that takes 3 seconds to run (incrementally reloading my blog in development), an extra 40ms doesn't make a noticeable difference. It's certainly not noticeable when I do a full blog build that takes 35 seconds.

**Comment by nickjj** [comment]
Thanks. If you want we can move this to an open discussion that stays open. Then other folks can contribute to the conversation too. If `mise` wins in the end and some other folks mention they notice big wins when using it I'd be open to switching over.

**Comment by nickjj** [comment]
I just enabled discussions in this repo, I thought they were already enabled. Seems like GitHub won't let you move an issue to a discussion for some reason. If you want to copy / paste your issue there that would be ok, this way you get credit for the discussion topic.
