### ISSUE TITLE
slow start-up while opening files using vim

### ISSUE THREAD

**Issue by otakenz** [nickjj/dotfiles#6]
Hi Nick,

I am experiencing super-slooow start-up time while opening files using vim.

For example .bashrc, .vimrc and so on..

It took ~60s to open a file using vim.

I used your .vimrc files and have the following removed because I do not use them and hoped to reduced latency. (but failed):
iamcco/markdown-preview.nvim (i dont use nvim so i guess this is not needed for me )
jvirtanen/vim-hcl
lifepillar/pgsql.vim
othree/html5.vim
pangloss/vim-javascript
tpope/vim-rails
vim-ruby/vim-ruby

I do not know what is happening, I have researched a few open discussions and I will list it here:
https://www.reddit.com/r/vim/comments/4yemwr/vim_startup_suddenly_very_slow/
https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow
https://github.com/microsoft/WSL/issues/5223

*Latest*
I think I know where is the problem, I have not set up x11 server yet, therefore it is not reachable after ~30s and have a timeout.
I find it from this reply. https://github.com/microsoft/WSL/issues/5223#issuecomment-652309457

**Comment by nickjj** [comment]
Hi,

If the problem persists even after setting up the x11 server, this usually has to do with a firewall getting in the way when it comes to clipboard access and the X server. A few folks have mentioned that.

Personally I don't run Windows firewall or any other software firewall tools, but if disabling it isn't an option you may want to follow the steps here https://skeptric.com/wsl2-xserver/.
